### PR TITLE
Difficulty with transitive dependencies while bumping ggcr

### PR DESCRIPTION
**Pull request by glyn**
This draft PR is evidence of the need for https://github.com/deislabs/cnab-go/issues/156.

### CODE REVIEW

**Comment by carolynvs** [comment]
I had a conversation with @radu-matei on his other PR https://github.com/deislabs/cnab-go/pull/150/files#r340859692 about how to properly manage dependencies. If you want to manage transitive dependencies with dep, that is how to do it.

**Comment by glyn** [comment]
> I had a conversation with @radu-matei on his other PR https://github.com/deislabs/cnab-go/pull/150/files#r340859692 about how to properly manage dependencies. If you want to manage transitive dependencies with dep, that is how to do it.

Thanks. Although that may be a necessary workaround with dep, it's not ideal because we then have to manually maintain the transitive dependencies and line them up accurately. I think that's reason enough alone to spur us on to go modules, which isn't that painful actually.

**Comment by squillace** [comment]
@glyn you, of course, realize that once you say something's not very painful, you end up being the sole point of responsibility, right? :-)

**Comment by carolynvs** [comment]
I'm just sharing what we can do today, if we aren't ready to jump the 🦈 and switch 15+ repos over to modules in a weekend. I am painfully aware that dep was killed before transitive dependency support was added...

If the group would like to move to modules immediately, I am not going to stand in their way but I will wait for someone else to volunteer. 😀

**Comment by glyn** [comment]
Thanks @carolynvs. When we move to modules, I propose we start on a Monday. Let's plan to keep our weekends for rest. :-)

**Comment by jlegrone** [comment]
@glyn is this still needed now that #161 is merged?

**Pull request closed without merging**
