### PR TITLE
Allow non-integer numbers in bundle.json 

### PR DESCRIPTION
**Pull request by carolynvs**
Now that we have switched to a canonical json library that supports
non-integer numbers, I've updated the bundle.json definition to use
float for: maximum, mimimum and multipleof.

The tests now use non-integer numbers to validate that a bundle using
values like 5.5 can be marshaled now.

🛑 This relies on #247 and upstream changes to the schemas in cnab-spec. Once that is merged and the spec tagged with a patch release, I'll rebase.

### CODE REVIEW

**Comment by radu-matei** [comment]
#247 was merged, I think this only needs a rebase now?

**Comment by carolynvs** [comment]
@radu-matei the tests won't pass until the spec is tagged. It is comparing my changes against the current spec, and so it's failing. Once I get Butcher's 👍 on the new release, then I can kick the build on this and it should be green.

**Comment by carolynvs** [comment]
@radu-matei @vdice Okay, the spec change has been merged. This is ready for review.

**Review by vdice — APPROVED** [review]
LGTM

**Comment by marseko** [comment]
> Now that we have switched to a canonical json library that supports
> non-integer numbers, I've updated the bundle.json definition to use
> float for: maximum, mimimum and multipleof.
> 
> The tests now use non-integer numbers to validate that a bundle using
> values like 5.5 can be marshaled now.
> 
> 🛑 This relies on #247 and upstream changes to the schemas in cnab-spec. Once that is merged and the spec tagged with a patch release, I'll rebase.
> 
>

**Pull request merged**
